# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runscompare', '0002_auto_20170211_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('run_id', models.CharField(default='0', max_length=100, primary_key=True, serialize=False)),
                ('suite_name', models.CharField(default='0', max_length=100)),
                ('duration', models.PositiveIntegerField()),
            ],
        ),
    ]
