# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runscompare', '0003_testexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='comments',
            field=models.CharField(default='no run comments', max_length=255),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='suite_name',
            field=models.CharField(default='Test suite name', max_length=100),
        ),
    ]
